# Base configs
baseurl: "https://snowy-base-5375.on.fleek.co/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Dewa Gde Adi"
subtitle: "See the world through my eyes!"
author: "Dewa Gde Adi"
header:
 title: "Photography"
 subtitle: "by Dewa Gde Adi"
footer:
 name: "Hey there, my name is Dewa Gde Adi"
 bio: "I am a developer and a tech aficionado from Indonesia. Love making teeny tiny apps solving tiny problems in life and now learning photography with my fuji xt20."
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/adxsck"
  twitter: ""
  instagram: "https://www.instagram.com/kapaktujengs"
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/cikiprik"
